---
- name: Install and configure NGINX
  hosts: nginx-1
  become: true
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Configure NGINX
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: restart nginx

    - name: Create custom index.html file
      copy:
        content: "<html><body><h1>Hello, World!</h1></body></html>"
        dest: /var/www/html/index.html

    - name: Clone git repository
      git:
        repo: https://github.com/sabreensalama/dockerize-node-app-task.git
        dest: /opt/dockerize-node-app-task
        version: main
    
    - name: Update package repositories
      become: true
      apt:
        update_cache: yes
    
    - name: Install Node.js and npm
      become: true
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Install app dependencies
      npm:
        path: /opt/dockerize-node-app-task
        state: present

    - name: Start app
      command: node server.js
      args:
        chdir: /opt/dockerize-node-app-task

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted