pipeline {
  agent any
  
  environment {
    APP_VERSION = '1.0.0'
  }
  
  parameters {
    string(name: 'NAME', defaultValue: 'Jenkins', description: 'Your name')
    booleanParam(name: 'GREET', defaultValue: true, description: 'Greet?')
  }
  
  stages {
    stage('Building') {
      when { expression { params.GREET } }
      steps {
        echo "Hello, ${params.NAME}!"
      }
    }
  }
}
