# Generated by Django 4.2.1 on 2023-05-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='birth_date',
            field=models.DateField(default='2023-5-5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='mobile',
            field=models.IntegerField(default=12345678910),
            preserve_default=False,
        ),
    ]
