@Library('my-shared-library') _

pipeline {
  agent any
  
  parameters {
    string(name: 'NAME', defaultValue: 'Jenkins', description: 'Your name')
  }
  
  stages {
    stage('Greeting') {
      steps {
        myStep(name: params.NAME)
      }
    }
  }
}
