apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: debug-container
    image: ubuntu:latest
    command: ["/bin/sh"]
    args: ["-c", "apt-get update && apt-get install -y curl && sleep 3600"]
